# Setup
title:               Marcos Ramon
tagline:             'Um site sobre filosofia, arte e tecnologia'
description:         'Sou professor de filosofia e pesquisador nas áreas de estética e cibercultura. Meus temas de interesse: tecnologia digital, arte, filosofia e cultura visual. Twitter: <a href="https://twitter.com/mrtollens">@mrtollens</a>'
url:                 https://marcosramon.net
baseurl:             ''
paginate:            5
permalink:           /:categories/:title/

# About/contact
author:
  name:              Marcos Ramon
  url:               https://twitter.com/mrtollens
  email:             contato@marcosramon.net

# Gems
plugins:
  - jekyll-paginate
  
# Custom vars
version:             1.1.0
google_analytics_id: UA-25904919-5

# Build settings
markdown:            kramdown
